### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'if [ -x /usr/local/bin/bash ];

### ISSUE THREAD

**Issue by lucbas** [cytopia/docker-yamllint#14]
Hi all

I try to run this on my gitlab repo.

.gitlab-ci.yml:
```yaml
stages:
 - lint
 
lint-yaml:
  stage: lint
  image: cytopia/yamllint
  script:
    - .
```

<img width="1359" alt="Screenshot 2020-05-19 at 13 19 39" src="https://user-images.githubusercontent.com/14868134/82320364-69c6b200-99d3-11ea-8cba-e7e791efffaa.png">

```bash
[0K[0K[36;1mRunning before_script and script[0;m
[0;mTraceback (most recent call last):
  File "/usr/bin/yamllint", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python3.8/site-packages/yamllint/cli.py", line 160, in run
    conf = YamlLintConfig(file=args.config_file)
  File "/usr/lib/python3.8/site-packages/yamllint/config.py", line 39, in __init__
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell not found\n\texit 1\nfi\n\n'
section_end:1589886959:build_script
[0Ksection_start:1589886959:after_script
[0K[0K[36;1mRunning after_script[0;m
[0;mTraceback (most recent call last):
  File "/usr/bin/yamllint", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python3.8/site-packages/yamllint/cli.py", line 160, in run
    conf = YamlLintConfig(file=args.config_file)
  File "/usr/lib/python3.8/site-packages/yamllint/config.py", line 39, in __init__
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell not found\n\texit 1\nfi\n\n'
section_end:1589886960:after_script
[0Ksection_start:1589886960:upload_artifacts_on_failure
[0K[0K[36;1mUploading artifacts for failed job[0;m
[0;msection_end:1589886962:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```

**Comment by THS-on** [comment]
Gitlab seems to run a shell detection script before running before running any other command in script. 
This currently seems to work. 
```yaml
stages:
 - lint

lint-yaml:
  stage: lint
  image:
    name: cytopia/yamllint
    entrypoint: ["/bin/ash", "-c"]
  script:
    - yamllint -f colored .
```

**Comment by cytopia** [comment]
@THS-on any idea what to change in the docker image itself to fix this behaviour for GitLab?

**Comment by THS-on** [comment]
You could provide a GitLab specific container with a shell as entry point, but I don't know if this is a good solution. I think the easiest currently way is just to document the override.

This behavior is documented here: https://docs.gitlab.com/runner/executors/docker.html#the-entrypoint

**Comment by cytopia** [comment]
@THS-on thanks for the snippet. Adding it to the documentation here: https://github.com/cytopia/docker-yamllint/pull/15
